---
name: Push to main

'on':
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
    paths-ignore:
      - 'README.md'
      - '.gitignore'

jobs:

  build:
    name: Build & Publish
    runs-on: ubuntu-22.04

    permissions:
      contents: 'read'
      id-token: 'write'

    timeout-minutes: 5

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/build

      - name: Publish
        uses: ./.github/actions/publish
